const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const distDir = path.join(__dirname, 'dist');
const stylesDir = path.join(__dirname, 'src', 'styles');
const componentsDir = path.join(__dirname, 'src', 'components');

// Ensure dist exists
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

console.log('[Cacao] Building frontend...');

// =========================================================================
// Auto-generate JS index files per component category
// =========================================================================

const jsCategories = ['layout', 'display', 'typography', 'form', 'charts'];

for (const cat of jsCategories) {
  const catDir = path.join(componentsDir, cat);
  const files = fs.readdirSync(catDir).filter(f => f.endsWith('.js') && f !== 'index.js');

  // Parse each file for exported function names
  const exports = [];
  for (const file of files) {
    const content = fs.readFileSync(path.join(catDir, file), 'utf8');
    // Match: export function Name(
    const funcMatches = [...content.matchAll(/export\s+function\s+(\w+)\s*\(/g)];
    const names = funcMatches.map(m => m[1]);
    // Match: export { Name1, Name2 }  (non-from re-exports of local names)
    const bracketMatches = [...content.matchAll(/export\s*\{([^}]+)\}(?!\s*from)/g)];
    for (const m of bracketMatches) {
      const exported = m[1].split(',').map(s => s.trim()).filter(Boolean);
      for (const name of exported) {
        if (!names.includes(name)) names.push(name);
      }
    }

    if (names.length > 0) {
      exports.push({ file, names });
    }
  }

  // Generate index.js
  const lines = exports.map(({ file, names }) =>
    `export { ${names.join(', ')} } from './${file}';`
  );
  const indexContent = lines.join('\n') + '\n';
  const indexPath = path.join(catDir, 'index.js');

  // Only write if changed
  const existing = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, 'utf8') : '';
  if (existing !== indexContent) {
    fs.writeFileSync(indexPath, indexContent);
    console.log(`[Cacao] Auto-generated ${cat}/index.js (${exports.length} modules, ${lines.length} exports)`);
  }
}

// =========================================================================
// Auto-generate LESS imports
// =========================================================================

const lessComponentsDir = path.join(stylesDir, 'components');
const allLessFiles = fs.readdirSync(lessComponentsDir)
  .filter(f => f.endsWith('.less'))
  .sort();

// Category LESS mapping: which component .less files belong to each category
// Files not listed here go into the full bundle only
const lessCategoryMap = {
  'cat-layout': ['admin', 'container', 'hero', 'split', 'stack', 'tabs'],
  'cat-display': [
    'accordion', 'alert', 'breadcrumb', 'card', 'diff', 'display',
    'file-tree', 'image', 'link-card', 'metric', 'modal', 'progress',
    'steps', 'subnav', 'table', 'timeline', 'tooltip', 'video',
  ],
  'cat-typography': ['typography', 'prose'],
  'cat-form': ['button', 'form', 'chat'],
  'cat-charts': ['charts'],
};

// Auto-detect: any .less file in components/ not in any category gets added
// to cat-display (the catch-all for display components)
const assignedFiles = new Set();
for (const files of Object.values(lessCategoryMap)) {
  files.forEach(f => assignedFiles.add(f));
}
for (const file of allLessFiles) {
  const name = file.replace('.less', '');
  // Skip files that are shared/non-component (branding, command-palette, toast are global)
  const globalFiles = ['branding', 'command-palette', 'toast'];
  if (!assignedFiles.has(name) && !globalFiles.includes(name)) {
    lessCategoryMap['cat-display'].push(name);
    lessCategoryMap['cat-display'].sort();
  }
}

// Generate category LESS files
for (const [cat, components] of Object.entries(lessCategoryMap)) {
  const imports = [
    '// Auto-generated by build.js — do not edit manually',
    '@import "variables.less";',
    '@import "mixins.less";',
    ...components.map(c => `@import "components/${c}.less";`),
  ].join('\n') + '\n';

  const catPath = path.join(stylesDir, `${cat}.less`);
  const existing = fs.existsSync(catPath) ? fs.readFileSync(catPath, 'utf8') : '';
  if (existing !== imports) {
    fs.writeFileSync(catPath, imports);
  }
}

// Generate full index.less (all components + themes + base)
const fullIndexLines = [
  '// Auto-generated by build.js — do not edit manually',
  '// Full Cacao stylesheet (all components)',
  '',
  '@import "variables.less";',
  '@import "mixins.less";',
  '@import "base.less";',
  '@import "layouts.less";',
  '',
  '// Themes',
  ...fs.readdirSync(path.join(stylesDir, 'themes'))
    .filter(f => f.endsWith('.less'))
    .sort()
    .map(f => `@import "themes/${f}";`),
  '',
  '// Components',
  ...allLessFiles.map(f => `@import "components/${f}";`),
];
const fullIndexContent = fullIndexLines.join('\n') + '\n';
const fullIndexPath = path.join(stylesDir, 'index.less');
const existingIndex = fs.existsSync(fullIndexPath) ? fs.readFileSync(fullIndexPath, 'utf8') : '';
if (existingIndex !== fullIndexContent) {
  fs.writeFileSync(fullIndexPath, fullIndexContent);
  console.log(`[Cacao] Auto-generated index.less (${allLessFiles.length} component files)`);
}

// =========================================================================
// Build CSS
// =========================================================================

console.log('[Cacao] Compiling LESS → CSS (full bundle)');
execSync('npx lessc src/styles/index.less dist/cacao.css', {
  cwd: __dirname,
  stdio: 'inherit'
});

const cssCategories = ['core', ...Object.keys(lessCategoryMap)];
console.log('[Cacao] Compiling category CSS:', cssCategories.join(', '));
for (const cat of cssCategories) {
  execSync(`npx lessc src/styles/${cat}.less dist/cacao-${cat}.css`, {
    cwd: __dirname,
    stdio: 'inherit'
  });
}

// =========================================================================
// Build JS
// =========================================================================

console.log('[Cacao] Bundling JS');
execSync('npx esbuild src/components/index.js --bundle --outfile=dist/cacao.js --format=iife --external:React --external:ReactDOM --external:Chart', {
  cwd: __dirname,
  stdio: 'inherit'
});

console.log('[Cacao] Build complete!');
