name: Bump Version on Dev

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Current Version
        id: current_version
        run: |
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Bump Version
        id: bump_version
        run: |
          current=${{ steps.current_version.outputs.version }}
          IFS='.' read -r -a parts <<< "$current"
          new_patch=$((parts[2] + 1))
          new_version="${parts[0]}.${parts[1]}.$new_patch"
          echo "$new_version" > VERSION
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update Version Files
        run: |
          NEW_VERSION=${{ steps.bump_version.outputs.new_version }}
          sed -i "s/version=['\"][^'\"]*['\"],/version='${NEW_VERSION}',/" setup.py
          sed -i "s/__version__ = \"[^\"]*\"/__version__ = \"${NEW_VERSION}\"/" cacao/__init__.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION setup.py cacao/__init__.py
          git commit -m "🔖 Version bump to v${{ steps.bump_version.outputs.new_version }} [skip ci]"
          git tag "v${{ steps.bump_version.outputs.new_version }}"
          git push origin dev --tags